# Generated by Django 3.2.9 on 2021-11-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
